source:      .
destination: ./_site
includes:    ./_includes

highlighter: pygments
permalink:   /:title

baseurl: https://seanfisher.co
title: "Sean Fisher - Principal Software Architect from New York City"
description: "Sean Fisher is a principal software architect from New York City. Specialties include WordPress, PHP, Laravel, WordPress VIP, web design and custom application development. Creates enterprise applications with WordPress"
root_desc: "Sean Fisher"

rdiscount:
  extensions: []

exclude: ['README.md', '.github', 'tailwind.config.js', 'src', 'css/screen.css', 'node_modules']
