source:      .
destination: ./_site
includes:    ./_includes

highlighter: pygments
permalink:   /:title

baseurl: https://seanfisher.co
title: "Sean Fisher - Software Architect Specializing in WordPress & Laravel"
description: "Sean Fisher is a principal software architect from NYC specializing in enterprise WordPress and Laravel solutions."
root_desc: "Sean Fisher"

rdiscount:
  extensions: []

exclude: ['README.md', '.github', 'tailwind.config.js', 'src', 'css/screen.css', 'node_modules', 'vendor']
